[package]
name = "whatlang-bindings"
version = "0.1.0"
authors = ["onetonfoot <onetonfoot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "whatlanglib"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
whatlang = "0.7.2"

[build-dependencies]
cbindgen = "0.13.2"